import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

const LOVABLE_API_KEY = Deno.env.get("LOVABLE_API_KEY");
const SUPABASE_URL = Deno.env.get("SUPABASE_URL");
const SUPABASE_SERVICE_ROLE_KEY = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");

// Categorías por audiencia
const TENANT_CATEGORIES = [
  "Cláusulas",
  "Fianzas", 
  "Derechos",
  "Subidas de renta",
  "Legislación",
  "Consejos",
];

const LANDLORD_CATEGORIES = [
  "Contratos",
  "Impagos",
  "Garantías",
  "Normativa",
  "Seguros",
  "Gestión",
];

const TITLE_FORMATS = [
  "X errores habituales al...",
  "Cómo gestionar cuando...",
  "Qué dice la LAU sobre...",
  "X aspectos clave de...",
  "Tus derechos ante...",
  "Cómo funcionan las...",
  "Lo que debes saber sobre...",
  "X preguntas frecuentes sobre...",
  "Claves para entender...",
  "Guía práctica:",
];

interface ExistingPost {
  title: string;
  category: string;
}

function getLeastUsedCategories(existingPosts: ExistingPost[], categories: string[]): string[] {
  const categoryCount = categories.map(cat => ({
    category: cat,
    count: existingPosts.filter(p => p.category === cat).length
  }));
  
  categoryCount.sort((a, b) => a.count - b.count);
  
  // Return the 2-3 least used categories
  return categoryCount.slice(0, 3).map(c => c.category);
}

async function generateImage(title: string, excerpt: string, category: string): Promise<string> {
  if (!LOVABLE_API_KEY || !SUPABASE_URL || !SUPABASE_SERVICE_ROLE_KEY) {
    console.log("Missing credentials for image generation");
    return "";
  }

  try {
    const imagePrompt = `Create a professional, clean editorial photograph for a Spanish real estate blog article.

Topic: "${title}"
${excerpt ? `Summary: "${excerpt}"` : ""}
${category ? `Category: ${category}` : ""}

Style requirements:
- Minimalist, premium, elegant aesthetic
- Warm cream and neutral tones matching a luxury editorial design
- Professional real estate or legal context
- Photorealistic, not illustrated
- NO text, NO watermarks, NO logos
- Soft natural lighting
- Clean composition with negative space
- 16:9 aspect ratio suitable for blog header`;

    console.log("Generating image with AI...");

    const response = await fetch("https://ai.gateway.lovable.dev/v1/chat/completions", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${LOVABLE_API_KEY}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        model: "google/gemini-2.5-flash-image",
        messages: [{ role: "user", content: imagePrompt }],
        modalities: ["image", "text"],
      }),
    });

    if (!response.ok) {
      console.error("Image generation failed:", response.status);
      return "";
    }

    const data = await response.json();
    const images = data.choices?.[0]?.message?.images;

    if (!images || images.length === 0) {
      console.log("No image generated by AI");
      return "";
    }

    const imageData = images[0].image_url?.url;
    if (!imageData) {
      return "";
    }

    // Extract base64 content
    const base64Match = imageData.match(/^data:image\/(\w+);base64,(.+)$/);
    if (!base64Match) {
      return "";
    }

    const imageFormat = base64Match[1];
    const base64Content = base64Match[2];

    // Decode base64 to binary
    const binaryString = atob(base64Content);
    const bytes = new Uint8Array(binaryString.length);
    for (let i = 0; i < binaryString.length; i++) {
      bytes[i] = binaryString.charCodeAt(i);
    }

    // Upload to Supabase Storage
    const supabase = createClient(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY);
    const fileName = `blog-${Date.now()}.${imageFormat}`;
    
    const { error: uploadError } = await supabase.storage
      .from("blog-images")
      .upload(fileName, bytes, {
        contentType: `image/${imageFormat}`,
        upsert: false,
      });

    if (uploadError) {
      console.error("Storage upload error:", uploadError);
      return "";
    }

    const { data: publicUrlData } = supabase.storage
      .from("blog-images")
      .getPublicUrl(fileName);

    console.log("Image uploaded successfully:", publicUrlData.publicUrl);
    return publicUrlData.publicUrl;
  } catch (error) {
    console.error("Error generating image:", error);
    return "";
  }
}

serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const { mode, prompt, existingPosts = [], audience = "inquilino" } = await req.json();

    if (!LOVABLE_API_KEY) {
      throw new Error("LOVABLE_API_KEY is not configured");
    }

    // Select categories based on audience
    const ALL_CATEGORIES = audience === "propietario" ? LANDLORD_CATEGORIES : TENANT_CATEGORIES;
    const targetAudience = audience === "propietario" ? "propietarios y arrendadores" : "inquilinos";

    // Get current date for temporal context
    const currentDate = new Date();
    const currentYear = currentDate.getFullYear();
    const months = ['enero', 'febrero', 'marzo', 'abril', 'mayo', 'junio', 'julio', 'agosto', 'septiembre', 'octubre', 'noviembre', 'diciembre'];
    const currentMonth = months[currentDate.getMonth()];

    const leastUsedCategories = getLeastUsedCategories(existingPosts, ALL_CATEGORIES);
    
    // Build context about existing posts
    const existingPostsContext = existingPosts.length > 0
      ? `\n\nPOSTS YA PUBLICADOS (NO repitas estos temas ni títulos similares):
${existingPosts.map((p: ExistingPost) => `- "${p.title}" (${p.category})`).join('\n')}

IMPORTANTE: 
- El título y el enfoque DEBEN ser completamente diferentes a los posts listados arriba
- NO uses palabras clave similares a títulos existentes
- Busca ángulos nuevos y originales`
      : "";

    const categoryGuidance = `\n\nCATEGORÍA PRIORITARIA:
Las siguientes categorías tienen menos contenido y deberían priorizarse:
${leastUsedCategories.map((c, i) => `${i + 1}. ${c}`).join('\n')}

Genera el post preferiblemente en una de estas categorías.`;

    // Audience-specific context
    const audienceContext = audience === "propietario"
      ? `Tu audiencia son PROPIETARIOS Y ARRENDADORES que quieren:
- Redactar contratos de alquiler seguros y válidos
- Protegerse ante impagos y morosos
- Conocer sus derechos y obligaciones según la LAU
- Gestionar correctamente fianzas y garantías adicionales
- Entender la normativa de zonas tensionadas
- Minimizar riesgos legales en el arrendamiento`
      : `Tu audiencia son INQUILINOS que quieren:
- Entender su contrato de alquiler
- Conocer sus derechos ante cláusulas abusivas
- Saber cómo reclamar ante problemas con el casero
- Estar informados sobre límites de subida de renta
- Proteger su fianza y depósitos
- Conocer sus derechos durante y al final del contrato`;

    let systemPrompt = `Eres un experto redactor de contenido legal inmobiliario en España.

FECHA ACTUAL: ${currentMonth} de ${currentYear}

CONTEXTO TEMPORAL OBLIGATORIO:
- Estamos en ${currentYear}. NUNCA escribas como si 2024 o 2025 fueran el presente o el futuro.
- El año 2024 ya pasó. El límite del 3% del IPC de 2024 ya NO está vigente.
- El año 2025 ya pasó. El IRAV entró en vigor el 1 de enero de 2025 y ya lleva más de un año funcionando.
- Cuando menciones fechas futuras, usa ${currentYear} o posteriores.
- Ejemplos correctos:
  - "Si tu contrato se actualiza en ${currentYear}..."
  - "Durante ${currentYear}, la normativa vigente establece..."
  - "Desde la entrada en vigor del IRAV en 2025, que ya lleva más de un año aplicándose..."
  - "El IRAV, que sustituyó al límite del 3% en enero de 2025..."
- Ejemplos INCORRECTOS (NO usar):
  - "Si tu contrato se actualiza en 2025..." (2025 ya pasó)
  - "A partir del 1 de enero de 2025..." (ya estamos después de esa fecha)
  - "Durante 2024..." como si fuera presente

Tu tarea es escribir artículos de blog profesionales, informativos y útiles para ${targetAudience}.

${audienceContext}

El artículo debe:
- Estar escrito en español de España
- Ser informativo y práctico
- Citar legislación relevante cuando sea apropiado (LAU, Código Civil, etc.)
- Tener un tono profesional pero accesible
- Incluir consejos prácticos

REGLAS DE LENGUAJE LEGAL (OBLIGATORIO):
- NUNCA uses afirmaciones absolutas como "es ilegal", "es nulo", "está prohibido"
- USA lenguaje matizado: "según la LAU", "se considera", "podría ser", "generalmente"
- SIEMPRE cita la fuente legal cuando menciones derechos u obligaciones
- NO actúes como asesor legal - el contenido es informativo, no constituye asesoramiento
- Evita imperativos como "debes" o "tienes que" - usa "es recomendable", "se aconseja"

Ejemplos de transformación:
- MAL: "Es ilegal cobrar más de 3 meses de fianza"
- BIEN: "Según el artículo 36 de la LAU, se considera contrario a la ley exigir más de 3 mensualidades en total"
- MAL: "Esa cláusula es nula"
- BIEN: "Esa cláusula podría considerarse nula según la LAU"
- MAL: "El casero no puede subir la renta"
- BIEN: "De acuerdo con la normativa vigente, las actualizaciones de renta estarían limitadas al índice IRAV"

VARIEDAD EN TÍTULOS (OBLIGATORIO):
NO uses siempre "Guía sobre..." o "Guía completa de...". Alterna entre estos formatos:
${TITLE_FORMATS.map(f => `- ${f}`).join('\n')}

TÍTULO (OBLIGATORIO - CRÍTICO):
- MÁXIMO 55 CARACTERES (Google trunca títulos largos en SERPs)
- Usa SOLO mayúscula inicial (sentence case)
- NO uses title case
- Evita tono alarmista o clickbait
- NO abuses de signos de interrogación

Ejemplos correctos (dentro del límite):
- "Cómo reclamar tu fianza paso a paso" (38 chars) ✓
- "5 cláusulas abusivas en contratos" (34 chars) ✓
- "Qué dice la LAU sobre subidas de renta" (39 chars) ✓

Ejemplos incorrectos (demasiado largos):
- "¿Puede el Casero Retener Parte de tu Fianza Si Hay Daños?" ❌
- "La guía completa sobre cómo reclamar tu fianza paso a paso" ❌
${existingPostsContext}
${categoryGuidance}

FAQs (OBLIGATORIO):
- Incluye 3-5 preguntas frecuentes relacionadas con el tema
- Las preguntas deben ser en primera persona: "¿Puedo...?", "¿Qué hago si...?", "¿Cuánto tiempo...?"
- Las respuestas deben ser concisas (2-3 frases, máximo 300 caracteres)
- Deben ser preguntas que alguien haría a Google o a un asistente de IA

Formato de respuesta OBLIGATORIO (JSON válido):
{
  "title": "Título informativo en sentence case (máximo 55 caracteres)",
  "excerpt": "Resumen corto del artículo en 2-3 frases (máximo 160 caracteres)",
  "content": "Contenido completo en formato Markdown. Usa ## para subtítulos, listas con -, y **negrita** para énfasis. Mínimo 800 palabras.",
  "category": "Una de: ${ALL_CATEGORIES.join(', ')}",
  "read_time": "X min (estimación de lectura)",
  "meta_description": "Descripción SEO del artículo (máximo 160 caracteres)",
  "keywords": ["array", "de", "palabras", "clave", "SEO"],
  "faqs": [
    {"question": "¿Pregunta frecuente 1?", "answer": "Respuesta concisa"},
    {"question": "¿Pregunta frecuente 2?", "answer": "Respuesta concisa"},
    {"question": "¿Pregunta frecuente 3?", "answer": "Respuesta concisa"}
  ]
}`;

    let userPrompt: string;

    if (mode === "auto") {
      if (audience === "propietario") {
        userPrompt = `Escribe un artículo ORIGINAL para PROPIETARIOS sobre un tema actual y relevante del alquiler en España. 

RECUERDA: Estamos en ${currentMonth} de ${currentYear}. El IRAV ya está en vigor desde enero de 2025 (hace más de un año).

REQUISITOS CLAVE:
1. El tema debe ser DIFERENTE a cualquier post ya publicado
2. Usa un formato de título CREATIVO (no "Guía sobre...")
3. Prioriza las categorías con menos contenido: ${leastUsedCategories.join(', ')}
4. Todas las referencias temporales deben reflejar que estamos en ${currentYear}

Temas sugeridos para PROPIETARIOS (elige uno que NO esté ya cubierto):
- Cómo redactar un contrato de alquiler seguro en ${currentYear}
- Qué hacer paso a paso ante un impago del inquilino
- Cláusulas imprescindibles para proteger tu vivienda
- Gestión de la fianza y garantías adicionales según la LAU
- Normativa de zonas tensionadas: qué implica para propietarios
- Seguros de impago: cuándo y por qué contratarlos
- Cómo seleccionar inquilinos de forma legal
- Fiscalidad del alquiler en ${currentYear}
- Derechos del propietario cuando el inquilino no cuida la vivienda
- Renovación vs. no renovación: opciones legales

Elige el tema que consideres más útil, actual y DIFERENTE a lo ya publicado.`;
      } else {
        userPrompt = `Escribe un artículo ORIGINAL para INQUILINOS sobre un tema actual y relevante del sector inmobiliario español de alquiler. 

RECUERDA: Estamos en ${currentMonth} de ${currentYear}. El IRAV ya está en vigor desde enero de 2025 (hace más de un año).

REQUISITOS CLAVE:
1. El tema debe ser DIFERENTE a cualquier post ya publicado
2. Usa un formato de título CREATIVO (no "Guía sobre...")
3. Prioriza las categorías con menos contenido: ${leastUsedCategories.join(', ')}
4. Todas las referencias temporales deben reflejar que estamos en ${currentYear}

Temas sugeridos para INQUILINOS (elige uno que NO esté ya cubierto):
- El IRAV en ${currentYear}: balance tras más de un año de aplicación
- Novedades legislativas de alquiler en ${currentYear}
- Derechos poco conocidos de los inquilinos
- Cómo reclamar ante problemas específicos con el casero
- Cláusulas abusivas comunes que pasan desapercibidas
- Consejos para negociar renovación del contrato en ${currentYear}
- Problemas de convivencia y comunidad
- Obras y reformas: derechos y obligaciones
- Suministros y gastos de comunidad
- Fin de contrato y prórrogas

Elige el tema que consideres más útil, actual y DIFERENTE a lo ya publicado.`;
      }
    } else {
      userPrompt = `Escribe un artículo de blog sobre el siguiente tema:

${prompt}

RECUERDA: Estamos en ${currentMonth} de ${currentYear}. El IRAV ya está en vigor desde enero de 2025.

IMPORTANTE:
- Usa un título CREATIVO (no "Guía sobre...")
- El enfoque debe ser original y diferente a posts existentes
- Todas las referencias temporales deben ser correctas (2024 y 2025 ya pasaron)
- El artículo está dirigido a ${targetAudience}
- Asegúrate de que el artículo sea completo, informativo y útil.`;
    }

    const response = await fetch("https://ai.gateway.lovable.dev/v1/chat/completions", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${LOVABLE_API_KEY}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        model: "google/gemini-2.5-pro",
        messages: [
          { role: "system", content: systemPrompt },
          { role: "user", content: userPrompt },
        ],
        temperature: 0.8,
      }),
    });

    if (!response.ok) {
      const errorText = await response.text();
      console.error("AI API error:", response.status, errorText);
      
      if (response.status === 429) {
        return new Response(
          JSON.stringify({ error: "Límite de peticiones excedido. Inténtalo de nuevo en unos minutos." }),
          { status: 429, headers: { ...corsHeaders, "Content-Type": "application/json" } }
        );
      }
      if (response.status === 402) {
        return new Response(
          JSON.stringify({ error: "Créditos agotados. Añade créditos a tu workspace." }),
          { status: 402, headers: { ...corsHeaders, "Content-Type": "application/json" } }
        );
      }
      
      throw new Error(`AI API error: ${response.status}`);
    }

    const data = await response.json();
    const content = data.choices?.[0]?.message?.content;

    if (!content) {
      throw new Error("No content returned from AI");
    }

    // Parse JSON from the response
    let blogPost;
    try {
      // Try to extract JSON from markdown code blocks if present
      const jsonMatch = content.match(/```(?:json)?\s*([\s\S]*?)```/);
      const jsonString = jsonMatch ? jsonMatch[1].trim() : content.trim();
      blogPost = JSON.parse(jsonString);
    } catch (parseError) {
      console.error("Error parsing AI response:", parseError);
      console.error("Raw content:", content);
      throw new Error("Error parsing blog post from AI response");
    }

    // Validate category is one of the allowed ones for this audience
    if (!ALL_CATEGORIES.includes(blogPost.category)) {
      const lowerCategory = blogPost.category.toLowerCase();
      const matchedCategory = ALL_CATEGORIES.find(c => 
        lowerCategory.includes(c.toLowerCase()) || c.toLowerCase().includes(lowerCategory)
      );
      blogPost.category = matchedCategory || leastUsedCategories[0];
    }

    // Generate image automatically
    console.log("Generating image for blog post...");
    const imageUrl = await generateImage(blogPost.title, blogPost.excerpt, blogPost.category);
    blogPost.image = imageUrl;

    return new Response(JSON.stringify(blogPost), {
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  } catch (error) {
    console.error("Error generating blog post:", error);
    return new Response(
      JSON.stringify({ error: error instanceof Error ? error.message : "Unknown error" }),
      { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  }
});
