import { buildBlogSystemPrompt } from "../_shared/blog-prompt.ts";
import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
import { MODELS, GATEWAY_URL } from "../_shared/models.ts";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

const LOVABLE_API_KEY = Deno.env.get("LOVABLE_API_KEY");
const SUPABASE_URL = Deno.env.get("SUPABASE_URL");
const SUPABASE_SERVICE_ROLE_KEY = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");

// Categorías por audiencia
const TENANT_CATEGORIES = [
  "Cláusulas",
  "Fianzas", 
  "Derechos",
  "Subidas de renta",
  "Legislación",
  "Consejos",
];

const LANDLORD_CATEGORIES = [
  "Contratos",
  "Impagos",
  "Garantías",
  "Normativa",
  "Seguros",
  "Gestión",
];

const TITLE_FORMATS = [
  "X errores habituales al...",
  "Cómo gestionar cuando...",
  "Qué dice la LAU sobre...",
  "X aspectos clave de...",
  "Tus derechos ante...",
  "Cómo funcionan las...",
  "Lo que debes saber sobre...",
  "X preguntas frecuentes sobre...",
  "Claves para entender...",
  "Guía práctica:",
];

interface ExistingPost {
  title: string;
  category: string;
}

function getLeastUsedCategories(existingPosts: ExistingPost[], categories: string[]): string[] {
  const categoryCount = categories.map(cat => ({
    category: cat,
    count: existingPosts.filter(p => p.category === cat).length
  }));
  
  categoryCount.sort((a, b) => a.count - b.count);
  
  // Return the 2-3 least used categories
  return categoryCount.slice(0, 3).map(c => c.category);
}

async function generateImage(title: string, excerpt: string, category: string): Promise<string> {
  if (!LOVABLE_API_KEY || !SUPABASE_URL || !SUPABASE_SERVICE_ROLE_KEY) {
    console.log("Missing credentials for image generation");
    return "";
  }

  try {
    const imagePrompt = `Create a professional, clean editorial photograph for a Spanish real estate blog article.

Topic: "${title}"
${excerpt ? `Summary: "${excerpt}"` : ""}
${category ? `Category: ${category}` : ""}

Style requirements:
- Minimalist, premium, elegant aesthetic
- Warm cream and neutral tones matching a luxury editorial design
- Professional real estate or legal context
- Photorealistic, not illustrated
- NO text, NO watermarks, NO logos
- Soft natural lighting
- Clean composition with negative space
- 16:9 aspect ratio suitable for blog header`;

    console.log("Generating image with AI...");

    const response = await fetch(GATEWAY_URL, {
      method: "POST",
      headers: {
        Authorization: `Bearer ${LOVABLE_API_KEY}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        model: MODELS.GEMINI_IMAGE,
        messages: [{ role: "user", content: imagePrompt }],
        modalities: ["image", "text"],
      }),
    });

    if (!response.ok) {
      console.error("Image generation failed:", response.status);
      return "";
    }

    const data = await response.json();
    const images = data.choices?.[0]?.message?.images;

    if (!images || images.length === 0) {
      console.log("No image generated by AI");
      return "";
    }

    const imageData = images[0].image_url?.url;
    if (!imageData) {
      return "";
    }

    // Extract base64 content
    const base64Match = imageData.match(/^data:image\/(\w+);base64,(.+)$/);
    if (!base64Match) {
      return "";
    }

    const imageFormat = base64Match[1];
    const base64Content = base64Match[2];

    // Decode base64 to binary
    const binaryString = atob(base64Content);
    const bytes = new Uint8Array(binaryString.length);
    for (let i = 0; i < binaryString.length; i++) {
      bytes[i] = binaryString.charCodeAt(i);
    }

    // Upload to Supabase Storage
    const supabase = createClient(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY);
    const fileName = `blog-${Date.now()}.${imageFormat}`;
    
    const { error: uploadError } = await supabase.storage
      .from("blog-images")
      .upload(fileName, bytes, {
        contentType: `image/${imageFormat}`,
        upsert: false,
      });

    if (uploadError) {
      console.error("Storage upload error:", uploadError);
      return "";
    }

    const { data: publicUrlData } = supabase.storage
      .from("blog-images")
      .getPublicUrl(fileName);

    console.log("Image uploaded successfully:", publicUrlData.publicUrl);
    return publicUrlData.publicUrl;
  } catch (error) {
    console.error("Error generating image:", error);
    return "";
  }
}

serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const { mode, prompt, existingPosts = [], audience = "inquilino" } = await req.json();

    if (!LOVABLE_API_KEY) {
      throw new Error("LOVABLE_API_KEY is not configured");
    }

    // Select categories based on audience
    const ALL_CATEGORIES = audience === "propietario" ? LANDLORD_CATEGORIES : TENANT_CATEGORIES;
    const targetAudience = audience === "propietario" ? "propietarios y arrendadores" : "inquilinos";

    // Get current date for temporal context
    const currentDate = new Date();
    const currentYear = currentDate.getFullYear();
    const months = ['enero', 'febrero', 'marzo', 'abril', 'mayo', 'junio', 'julio', 'agosto', 'septiembre', 'octubre', 'noviembre', 'diciembre'];
    const currentMonth = months[currentDate.getMonth()];

    const leastUsedCategories = getLeastUsedCategories(existingPosts, ALL_CATEGORIES);
    
    // Build context about existing posts
    const existingPostsContext = existingPosts.length > 0
      ? `\n\nPOSTS YA PUBLICADOS (NO repitas estos temas ni títulos similares):
${existingPosts.map((p: ExistingPost) => `- "${p.title}" (${p.category})`).join('\n')}

IMPORTANTE: 
- El título y el enfoque DEBEN ser completamente diferentes a los posts listados arriba
- NO uses palabras clave similares a títulos existentes
- Busca ángulos nuevos y originales`
      : "";

    const categoryGuidance = `\n\nCATEGORÍA PRIORITARIA:
Las siguientes categorías tienen menos contenido y deberían priorizarse:
${leastUsedCategories.map((c, i) => `${i + 1}. ${c}`).join('\n')}

Genera el post preferiblemente en una de estas categorías.`;


    const blogAudience: "inquilino" | "propietario" = audience === "propietario" ? "propietario" : "inquilino";

    const systemPrompt = `${buildBlogSystemPrompt(blogAudience)}

FECHA ACTUAL: ${currentMonth} de ${currentYear}.
${existingPostsContext}
${categoryGuidance}

FORMATO DE SALIDA (JSON):
{
  "title": "título en sentence case (máx 60 caracteres)",
  "excerpt": "resumen concreto de 140-155 caracteres",
  "content": "cuerpo completo en HTML (h2/h3, sin h1), mínimo 900 palabras",
  "category": "una de: ${ALL_CATEGORIES.join(", ")}",
  "read_time": "X min",
  "meta_description": "140-155 caracteres",
  "keywords": ["palabras", "clave"],
  "faqs": [{"question": "¿...?", "answer": "respuesta de 2-3 frases"}]
}
"faqs" puede ser una lista vacía; úsala solo si el tema lo pide.`;

    let userPrompt: string;

    if (mode === "auto") {
      userPrompt = `Escribe un artículo original para ${targetAudience} sobre un problema real del alquiler de vivienda en España.

- El tema debe ser distinto de los ya publicados; prioriza estas categorías: ${leastUsedCategories.join(", ")}.
- Decide la estructura según el tema. No uses el esqueleto de siempre.
- Cita el artículo concreto cada vez que afirmes algo legal.`;
    } else {
      userPrompt = `Escribe un artículo para ${targetAudience} sobre este tema:

${prompt}

- Enfoque propio, distinto de los posts existentes.
- Decide la estructura según el tema. No uses el esqueleto de siempre.
- Cita el artículo concreto cada vez que afirmes algo legal.`;
    }

    const response = await fetch(GATEWAY_URL, {
      method: "POST",
      headers: {
        Authorization: `Bearer ${LOVABLE_API_KEY}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        model: MODELS.GEMINI_PRO,
        messages: [
          { role: "system", content: systemPrompt },
          { role: "user", content: userPrompt },
        ],
        temperature: 0.8,
        response_format: { type: "json_object" },
      }),
    });

    if (!response.ok) {
      const errorText = await response.text();
      console.error("AI API error:", response.status, errorText);
      
      if (response.status === 429) {
        return new Response(
          JSON.stringify({ error: "Límite de peticiones excedido. Inténtalo de nuevo en unos minutos." }),
          { status: 429, headers: { ...corsHeaders, "Content-Type": "application/json" } }
        );
      }
      if (response.status === 402) {
        return new Response(
          JSON.stringify({ error: "Créditos agotados. Añade créditos a tu workspace." }),
          { status: 402, headers: { ...corsHeaders, "Content-Type": "application/json" } }
        );
      }
      
      throw new Error(`AI API error: ${response.status}`);
    }

    const data = await response.json();
    const content = data.choices?.[0]?.message?.content;

    if (!content) {
      throw new Error("No content returned from AI");
    }

    // Parse JSON from the response
    let blogPost;
    try {
      // Try to extract JSON from markdown code blocks if present
      const jsonMatch = content.match(/```(?:json)?\s*([\s\S]*?)```/);
      const jsonString = jsonMatch ? jsonMatch[1].trim() : content.trim();
      blogPost = JSON.parse(jsonString);
    } catch (parseError) {
      console.error("Error parsing AI response:", parseError);
      console.error("Raw content:", content);
      throw new Error("Error parsing blog post from AI response");
    }

    // Validate category is one of the allowed ones for this audience
    if (!ALL_CATEGORIES.includes(blogPost.category)) {
      const lowerCategory = blogPost.category.toLowerCase();
      const matchedCategory = ALL_CATEGORIES.find(c => 
        lowerCategory.includes(c.toLowerCase()) || c.toLowerCase().includes(lowerCategory)
      );
      blogPost.category = matchedCategory || leastUsedCategories[0];
    }

    // Generate image automatically
    console.log("Generating image for blog post...");
    const imageUrl = await generateImage(blogPost.title, blogPost.excerpt, blogPost.category);
    blogPost.image = imageUrl;

    return new Response(JSON.stringify(blogPost), {
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  } catch (error) {
    console.error("Error generating blog post:", error);
    return new Response(
      JSON.stringify({ error: error instanceof Error ? error.message : "Unknown error" }),
      { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  }
});
